name: CI for main Branch

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Frontend CI
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Test frontend
        run: |
          cd frontend
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No test script found for frontend"
          fi

      - name: Build frontend
        run: |
          cd frontend
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found for frontend"
          fi

      # Server CI
      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Test server
        run: |
          cd server
          if npm run | grep -q "test"; then
            npm test
          else
            echo "No test script found for server"
          fi

      - name: Build server
        run: |
          cd server
          if npm run | grep -q "build"; then
            npm run build
          else
            echo "No build script found for server"
          fi
